import { NotificationSummary } from '../types';
import { GreenApiService } from './greenApi';

export class NotificationService {
  private greenApi: GreenApiService;

  constructor() {
    this.greenApi = new GreenApiService();
  }

  async sendSummary(summary: NotificationSummary, recipientPhone: string): Promise<void> {
    const message = this.formatSummaryMessage(summary);
    
    try {
      await this.greenApi.sendMessage(`${recipientPhone}@c.us`, message);
      console.log('Summary notification sent successfully');
    } catch (error) {
      console.error('Failed to send summary notification:', error);
      throw error;
    }
  }

  private formatSummaryMessage(summary: NotificationSummary): string {
    const { totalMessages, detectedMeetings, missingFromCalendar, conflicts } = summary;
    
    let message = `📅 WhatsApp Calendar Audit Summary\n\n`;
    message += `🔍 Analyzed ${totalMessages} WhatsApp messages from last 3 days\n`;
    message += `📋 Detected ${detectedMeetings} potential meetings\n`;
    message += `❌ ${missingFromCalendar} missing from calendar\n`;
    message += `⚠️ ${conflicts} schedule conflicts found\n\n`;

    if (missingFromCalendar > 0 || conflicts > 0) {
      message += `📝 Action Required:\n`;
      
      const actionItems = summary.details.filter(detail => 
        detail.status === 'Missing from calendar' || 
        detail.status === 'Schedule conflict detected'
      );

      actionItems.forEach((detail, index) => {
        message += `\n${index + 1}. ${detail.senderName}:\n`;
        message += `   "${detail.meetingText}${detail.meetingText.length >= 100 ? '...' : ''}"\n`;
        message += `   Status: ${detail.status}\n`;
        message += `   Recommendation: ${detail.recommendation}\n`;
      });
    } else {
      message += `✅ All detected meetings are properly scheduled!\n`;
    }

    message += `\n⏰ Report generated at ${new Date().toLocaleString('he-IL')}`;
    
    return message;
  }

  formatDetailedReport(summary: NotificationSummary): string {
    let report = `📊 Detailed WhatsApp Calendar Audit Report\n`;
    report += `${'='.repeat(40)}\n\n`;
    
    report += `📈 Statistics:\n`;
    report += `• Total messages analyzed: ${summary.totalMessages}\n`;
    report += `• Meetings detected: ${summary.detectedMeetings}\n`;
    report += `• Missing from calendar: ${summary.missingFromCalendar}\n`;
    report += `• Schedule conflicts: ${summary.conflicts}\n\n`;
    
    if (summary.details.length > 0) {
      report += `📋 Detailed Breakdown:\n`;
      report += `${'-'.repeat(30)}\n`;
      
      summary.details.forEach((detail, index) => {
        report += `\n${index + 1}. Contact: ${detail.senderName}\n`;
        report += `   Message: "${detail.meetingText}${detail.meetingText.length >= 100 ? '...' : ''}"\n`;
        report += `   Status: ${detail.status}\n`;
        report += `   Action: ${detail.recommendation}\n`;
        
        if (index < summary.details.length - 1) {
          report += `   ${'-'.repeat(25)}\n`;
        }
      });
    }
    
    report += `\n\n🤖 Generated by WhatsApp Calendar Audit Service`;
    report += `\n⏰ ${new Date().toLocaleString('he-IL')}`;
    
    return report;
  }
}