name: Daily WhatsApp Calendar Audit

on:
  schedule:
    # Run at 9:30 PM Israel time (18:30 UTC in winter, 19:30 UTC in summer)
    - cron: '30 19 * * *'  # Adjust for daylight saving
  workflow_dispatch:  # Allow manual trigger

jobs:
  audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Create data directories
      run: mkdir -p data/users config logs
      
    - name: Restore user data
      run: |
        # Method 1: Direct JSON (cleaned) - try this first
        echo '${{ secrets.SHAHAR_USER_DATA }}' | tr -d '\n\r' > data/users/1d7c2a42-ae77-4f4c-969d-f43bde9408d9.json
        echo '${{ secrets.YONIT_USER_DATA }}' | tr -d '\n\r' > data/users/a4139531-7b4b-42fd-9301-dd2cb9caaf88.json
        
        # Method 2: Base64 fallback (if secrets exist)
        if [ ! -z '${{ secrets.SHAHAR_USER_DATA_BASE64 }}' ]; then
          echo '${{ secrets.SHAHAR_USER_DATA_BASE64 }}' | base64 -d > data/users/1d7c2a42-ae77-4f4c-969d-f43bde9408d9.json
        fi
        if [ ! -z '${{ secrets.YONIT_USER_DATA_BASE64 }}' ]; then
          echo '${{ secrets.YONIT_USER_DATA_BASE64 }}' | base64 -d > data/users/a4139531-7b4b-42fd-9301-dd2cb9caaf88.json
        fi
        
        # Debug: Show file contents
        echo "📄 Shahar file size: $(wc -c < data/users/1d7c2a42-ae77-4f4c-969d-f43bde9408d9.json)"
        echo "📄 Yonit file size: $(wc -c < data/users/a4139531-7b4b-42fd-9301-dd2cb9caaf88.json)"
        echo "📄 Shahar preview: $(head -c 100 data/users/1d7c2a42-ae77-4f4c-969d-f43bde9408d9.json)"
        
    - name: Run daily audit
      run: node run-audit.js